# Generated by Django 4.2.4 on 2023-08-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0003_onlineshop_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlineshop',
            table='advertisements',
        ),
    ]
